services:
  - type: web
    name: old-lfews
    env: python
    buildCommand: "./build_files.sh"
    startCommand: "gunicorn lfews.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: old-lfews-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: old-lfews-db
    databaseName: old-lfews
    user: old-lfews 