# Generated by Django 5.1.4 on 2025-05-27 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterLevelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('green_threshold', models.FloatField()),
                ('yellow_threshold', models.FloatField()),
                ('orange_threshold', models.FloatField()),
                ('red_threshold', models.FloatField()),
                ('modbus_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('modbus_port', models.IntegerField(default=100)),
                ('unit_id', models.IntegerField(default=1)),
                ('register_address', models.IntegerField(default=6)),
                ('status', models.CharField(default='active', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecastStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(default='active', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('station_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='active', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.FloatField()),
                ('type', models.CharField(default='live', max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app.waterlevelstation')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('precipitation_probability', models.FloatField(blank=True, null=True)),
                ('relative_humidity', models.FloatField(blank=True, null=True)),
                ('dew_point', models.FloatField(blank=True, null=True)),
                ('fetch_time', models.DateTimeField(auto_now_add=True)),
                ('forecast_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='app.weatherforecaststation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('humidity', models.CharField(blank=True, max_length=255, null=True)),
                ('wind_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=255, null=True)),
                ('pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('precipitation_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('precipitation_total', models.CharField(blank=True, max_length=255, null=True)),
                ('uv', models.CharField(blank=True, max_length=255, null=True)),
                ('solar_radiation', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source', models.CharField(default='api', max_length=255)),
                ('weather_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='app.weatherstation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
