# Generated by Django 5.1.4 on 2025-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevelstation',
            name='modbus_ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
