# Generated by Django 5.1.4 on 2025-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recreate_fields'),
        ('app', '0002_update_field_lengths'),
    ]

    operations = [
    ]
