# Generated by Django 5.1.4 on 2025-05-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_waterlevelstation_modbus_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.CharField(max_length=255),
        ),
    ]
