# Generated by Django 5.1.4 on 2025-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_0002_recreate_fields_0002_update_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterleveldata',
            name='type',
            field=models.CharField(default='live', editable=False, max_length=255),
        ),
    ]
