# Generated by Django 5.1.4 on 2025-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_logs_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevelstation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='waterlevelstation',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
