# Generated by Django 5.1.4 on 2025-05-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_waterleveldata_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterleveldata',
            name='type',
        ),
    ]
