# Generated by Django 5.1.4 on 2025-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_waterlevelstation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherforecaststation',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherforecaststation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherforecaststation',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
